### ISSUE TITLE
Add web platform tests 

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#12]
This issue is about adding new tests for the Screen Capture Mouse Events specification.

## Creating a new directory for the tests

Currently, it does not seem there is any directory for these tests. We could either put them in

* a new `screen-capture-mouse-events/` directory OR
* a new subdirectory `mouse-events/` of the existing `screen-capture/` directory for the Screen Capture spec?

@eladalon1983  Note sure what is preferable?

We would also add a `META.yml` file with the spec link and suggested reviewers.

## Importing tests from Chromium

While implementing a prototype for Chromium, I wrote a couple of tests:

### Some tests verifying `CaptureController` is a `TargetEvent` (see https://chromium-review.googlesource.com/c/chromium/src/+/4542243). 

```
screen-capture/idlharness.https.window.js
screen-capture/capture-controller-event-target.https.window.js
```

These are in `screen-capture/` since that's really described in the Screen Capture spec and cannot be landed until https://github.com/w3c/mediacapture-screen-share/issues/268 is fixed.

### Some tests for the IDL introduced in the Screen Capture Mouse Events spec (see https://chromium-review.googlesource.com/c/chromium/src/+/4517372). 

```
wpt_internal/screen-capture-mouse-events/capture-controller-oncapturedmousechange.https.html
wpt_internal/screen-capture-mouse-events/captured-mouse-event-constructor.html
wpt_internal/screen-capture-mouse-events/captured-mouse-event-constructor-inherited.html
wpt_internal/screen-capture-mouse-events/idlharness.https.window.js
```

These tests are currently internal to Chromium because (1) we don't have a directory in WPT for the new spec yet, (2) https://github.com/w3c/mediacapture-screen-share/issues/268 is not fixed yet (3) the idlharness one relies on an internal screen-capture-mouse-events.tentative.idl because screen capture mouse events spec is not included in webref (probably related to https://github.com/w3c/browser-specs/issues/945 and issue #20).

### Manual test for Screen Capture Mouse Events spec (see https://chromium-review.googlesource.com/c/chromium/src/+/4549484)

```
screen-capture/capturing-mouse-coordinates-manual.tentative.https.html
```

This is a manual test because I don't think we have an API in WPT for starting a screen share and performing mouse moves. It's also in `screen-capture/` because we don't have a location for Screen Capture Mouse Events spec.

**Comment by eladalon1983** [comment]
> a new `screen-capture-mouse-events/` directory OR

I think I prefer this option.
Quick note that I've gone ahead, taken the plunge, and renamed this repo to `captured-mouse-event`. So probably that.

**Comment by fred-wang** [comment]
OK, so the status is:

1. We have a `screen-capture-mouse-events/` directory to put the tests in.
2. https://github.com/w3c/mediacapture-screen-share/issues/268 is fixed and that's reflected in WPT's [screen-capture.idl](https://github.com/web-platform-tests/wpt/blob/master/interfaces/screen-capture.idl)
3. We are working in [adding Captured Mouse Events to browser specs](https://github.com/w3c/browser-specs/pull/994) which would allow new IDLs to be extracted by [Reffy](https://github.com/w3c/reffy), to be imported into [webref](https://github.com/w3c/webref) and finally copied into [WPT's interfaces](https://github.com/web-platform-tests/wpt/tree/master/interfaces).

In any case I opened a [CL to land the tests in the WPT repo](https://chromium-review.googlesource.com/c/chromium/src/+/4661012). When it lands I think we can close this issue and open an issue in another bug tracker to replace `tentative.idl` with the actual IDL provided by (3).

**Comment by fred-wang** [comment]
I expect https://chromium-review.googlesource.com/c/chromium/src/+/4661012 to get merged soon, so closing this.
