### ISSUE TITLE
Peer-to-peer transfer of the mouse events?

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#13]
The two [uses cases](https://screen-share.github.io/mouse-events/#use-cases) mentioned peer-to-peer transfer of the mouse events. This can currently be performed as follows:

1. Create a `CaptureController` object and add a listener for `CapturedMouseEvents`.
2. Call `navigator.mediaDevices.getDisplayMedia` with that `CaptureController` object in order to retrieve a `MediaStream` with the captured screen.
3. In the `CaptureController` object's listener use the `RTCDataChannel` to transmit the mouse events.
4. The remote peer retrieves these mouse events by listening to message events on their own `RTCDataChannel`.

An alternative (which is not possible with the current version of the spec) would be to transmit the `MediaStreamTrack` corresponding to the captured video via `RTCRtpSender.addTrack()` and the remote peer to listen to `CapturedMouseEvents` on their `RTCRtpSender.track`. User agents would have to implement some internal magic to transmit the `CapturedMouseEvents` from the local `MediaStreamTrack` to the remote `MediaStreamTrack` via the WebRTC connection, and to dispatch events on the remote `MediaStreamTrack`.

For this alternative approach, note that `MediaStreamTrack` already has an `EventTarget` so `CapturedMouseEvents` could just be dispatched on that object, removing the need to rely on `CaptureController` (see #9). For Chromium, it seems that would simplify a bit the [implementation](https://chromium-review.googlesource.com/c/chromium/src/+/4549484) by avoiding to (a) forward the events from the `MediaStreamTrack` to the `CaptureController` and to (b) keep the `CaptureController` object alive during the capture session. I don't know how complicate would be the magic to transmit the mouse events via the WebRTC connection, though...

Anyway, do I understand correctly that the spec implicitly suggests to use `RTCDataChannel` for peer-to-peer transfer of the mouse events? If so, does it make sense to make it a bit more explicit?

Have we considered the alternative approach of making the `MediaStreamTrack` object a target for `CapturedMouseEvents`? If it has been discarded, does it make sense to have a note in the spec explaining the rationale? Or maybe this approach is desirable and we should investigate changing the spec to make it possible?

**Comment by eladalon1983** [comment]
> An alternative (which is not possible with the current version of the spec)

I believe you mean that the spec does not introduce the mechanisms that'd make that possible. But neither does the spec forbid it.

> removing the need to rely on CaptureController (see https://github.com/screen-share/mouse-events/issues/9)

My reading is that there is budding consensus in the WebRTC WG to make CaptureController into an EventTarget, and that it would be done next week. So I don't think we should look for ways around that atm.

> An alternative [...] would be to transmit the MediaStreamTrack corresponding to the captured video via RTCRtpSender.addTrack() and the remote peer to listen to CapturedMouseEvents on their RTCRtpSender.track.
> [...]
> I don't know how complicate would be the magic to transmit the mouse events via the WebRTC connection, though...

Magic would not be required, but rather, a standardized way to transmit mouse events over RTP/RTCP. I'd advise against embarking on that endeavor at this point. I think that'd take quite a bit of work (compared to letting each application come up with its own mechanism of transmitting the information, possibly using a data channel, but not necessarily).

> Anyway, do I understand correctly that the spec implicitly suggests to use RTCDataChannel for peer-to-peer transfer of the mouse events? If so, does it make sense to make it a bit more explicit?

I don't think the spec should suggest a mechanism, but it can make reference to the possibility of doing that over a data channel, by way of illustration of what this spec enables.

**Comment by fred-wang** [comment]
> I believe you mean that the spec does not introduce the mechanisms that'd make that possible. But neither does the spec forbid it.

Right, that's what I mean!

> My reading is that there is budding consensus in the WebRTC WG to make CaptureController into an EventTarget, and that it would be done next week. So I don't think we should look for ways around that atm.
> Magic would not be required, but rather, a standardized way to transmit mouse events over RTP/RTCP. I'd advise against embarking on that endeavor at this point. I think that'd take quite a bit of work (compared to letting each application come up with its own mechanism of transmitting the information, possibly using a data channel, but not necessarily).

Right, we would follow a standardized way for sure, by "magic" I meant that I don't know yet how it would look like as I'm not familiar yet with this part of the code! I'm fine with continuing with the CaptureController option for now. My main concern was whether I misinterpreted the peer-to-peer transfer to be done by `RTCDataChannel` rather than `MediaStream`, as the latter option would need extra mechanism.

 > I don't think the spec should suggest a mechanism, but it can make reference to the possibility of doing that over a data channel, by way of illustration of what this spec enables.

Sure, I think in general adding examples would help for people (like me) who first read this spec without being familiar  with the concepts from the WebRTC / Media Capture and Streams / Screen Capture specs...

**Comment by eladalon1983** [comment]
> by "magic" I meant

I use the word "magic" like that all the time. :-)

`RTCDataChannel` allows sending arbitrary data. This requires extra work of the applications on both ends, and makes potential interoperability between different applications a challenge.

But it also means that:
* The frequency and format of events is fully within the control of the applications.
* Transmitted data can be batched if desired.
* Batching can be done together with other forms of transmitted data.
* The format and content of captured-mouse-coordinates events needs not be locked in at this point.

The [alternative with RTCRtpSender.track](https://github.com/screen-share/mouse-events/issues/13#issue-1765421377) would require much work. IMHO, that'd be premature.

**Comment by fred-wang** [comment]
Agree. I would also add that it's good to have a first implementation for web developers, they can rely on `RTCDataChannel` , do their own experiments and gather useful feedback for future improvements/extensions of the spec.

**Comment by fred-wang** [comment]
https://github.com/screen-share/mouse-events/pull/18 contains an illustration of this can be done with `RTCDataChannel`. I'm keeping this open if `MediaStreamTrack` is considered in the future.

**Comment by eladalon1983** [comment]
I don't think it will be done in the foreseeable future. Shall we close this issue and reopen when it becomes relevant? (When inactive issues are kept open, it makes it hard to iterate through all of the open-and-active ones and make progress.)

**Comment by fred-wang** [comment]
@eladalon1983 As I mention on the other issue, closing issues is not the right approach for prioritization IMHO. We can have a label for issues to consider in the future, but if we close the issue I'm doubtful we will ever look into them again, it will be very easy to forget. Also if someone wants to report a new issue, they will likely only look for duplicate in open issues not to "closed one with a special label". So I'd rather keep issues open until they are resolved and rely on label to include/exclude them from the list. GitHub UI makes it very easy.

On this particular issue, I guess https://github.com/screen-share/captured-mouse-events/pull/18 addresses the concern about how to do p2p transfer with what we have currently. I think we can open a separate issue about the idea of having events handled via `MediaStreamTrack` and transferred automatically by the UA.

**Comment by fred-wang** [comment]
> On this particular issue, I guess https://github.com/screen-share/captured-mouse-events/pull/18 addresses the concern about how to do p2p transfer with what we have currently. I think we can open a separate issue about the idea of having events handled via MediaStreamTrack and transferred automatically by the UA.

OK so let's close this issue. About having events handled via MediaStreamTrack and transferred automatically p2p, let's wait that any user / web dev made such a request.
