### ISSUE TITLE
Adding listeners to CaptureController after calling getDisplayMedia()?

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#14]
This was mentioned in discussions on Chromium's design doc and I noticed the same when implementing [my prototype](https://chromium-review.googlesource.com/c/chromium/src/+/4549484) so I believe it's worth having an entry here.

Consider the following code where listeners are set after the call to `getDisplayMedia()`:

```
    let controller = new CaptureController();
    await navigator.mediaDevices.getDisplayMedia({controller: controller});
    controller.oncapturedmousechange = ...;
    controller.addEventListener("capturedmousechange", ...);
```

The spec does not say anything about these cases, so I understand that the two callbacks would be called with mouse events happening after they are registered. This is what my prototype does and is covered by unit tests...

However, making that possible means that we always have to perform some setup for mouse event transmission (in the case of my prototype, a series of callbacks) and try and send the events (in the case of my prototype, through the series of callbacks) even if `CaptureController` does not initially have any listener attached and even if it never has any one attached later. Alternatively, we can postpone this setup to when a listener is attached but then we would still need some extra work (in the case of Chromium, I imagine passing a message 'listener attached' through the various C++ objects involved).

Current usages of `CaptureController` don't need these mouse events and it may remain the most usual case in the future. So if the extra work is a concern, there can be two alternatives to address that:

1. If this use case of attaching listener after `getDisplayMedia()` is not important, maybe we can forbid it by making addEventListener throw an exception when that happens.

2. Or as that was suggested on the design doc, add an option on `CaptureController` (that must be set before the `getDisplayMedia` call, e.g. in the constructor) to inform it will receive mouse coordinates events in the future.

**Comment by eladalon1983** [comment]
Would you like to present this question to the Screen Capture CG in the upcoming Monday meeting? We could schedule a 20 minutes for this; would that be enough?

**Comment by fred-wang** [comment]
My understanding of yesterday's discussion at the Screen Capture CG meeting. Feel free to correct/elaborate or add your own opinion on the topic.

The consensus seems to be that not adding any restriction on when addEventListener is called is more natural for web developers i.e. keep the current version of the spec.

Sending mouse events from the low-level part (observing mouse changes) to the CaptureController (dispatching DOM events) may cause some latency due to e.g. IPC calls. This would make the performance worse for the case when no event handlers are registered at all.

Browsers can implement an optimization by doing that only when at least one listener is registered i.e. CaptureController would tell the low-level part to start sending events when the first event listener is registered, and maybe to stop when the last event listener is removed. These messages can themselves cause some latency but people didn't consider that a big issue. If necessary, we may add some text in the spec to suggest such an optimization to implementers.

Finally there was also some comment that if permissions are required to enable that feature, it could make sense to use that information to decide whether to enable the transmission of mouse events. For mouse coordinates this is not required though (see #17).

**Comment by eladalon1983** [comment]
Thanks again for presenting yesterday, Frédéric!
* [Slides](https://docs.google.com/presentation/d/1OLivIHYOLKjsFnINq2nibBk9RtwCQjkEyIazyiFzhh0/edit#slide=id.g250e4f3769e_0_11)
* [Recording](https://drive.google.com/file/d/1OW6kcQbX5XQLqJSFaDabtUJTJcRiWZU6/view?usp=sharing) (1:05:50)
* [Minutes](https://github.com/screen-share/meetings/blob/main/minutes/2023-06-26.md#capturedmouseevent-listener-frederic-wang)

> The consensus seems to be that not adding any restriction on when addEventListener is called is more natural for web developers i.e. keep the current version of the spec.

That's my understanding as well.

> These sync messages can themselves cause some latency but people didn't consider that a big issue.

nit: I don't think these will need to be blocking IPCs. If a UA optimizes by only sending these messages when there is a handler, then registering the handler will incur a delay until events starts flowing, but that won't block. Or wdyt?

**Comment by fred-wang** [comment]
> nit: I don't think these will need to be blocking IPCs. If a UA optimizes by only sending these messages when there is a handler, then registering the handler will incur a delay until events starts flowing, but that won't block. Or wdyt?

Yes. I misused "sync" to mean that these messages make the two ends of the communication channel in sync regarding the fact that mouse events must be sent or not.

**Comment by eladalon1983** [comment]
Should we close this issue now, do you think?

**Comment by fred-wang** [comment]
It seems there were no more feedback from CG members so I guess we'll follow the consensus mentioned above, which does not need spec change. We can always open new issues if we find necessary to give more details in the spec.
