### ISSUE TITLE
Elaborate a bit more on use case "efficiency enhancements during RTC"

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#15]
This is [explained in the current spec](https://screen-share.github.io/mouse-events/#use-case-2) but the details about not drawing mouse coordinates in the video frames is not very explicit IMHO and at least not obvious for people who are not familiar with the details the specs from the WebRTC WG.

The design doc linked from the [intent to prototype](https://groups.google.com/a/chromium.org/g/blink-dev/c/DYb5fXICJvo) slightly more explicit: use [cursor constraint](https://www.w3.org/TR/screen-capture/#dfn-cursor). This is also mentioned in the [README](https://github.com/screen-share/mouse-events/blob/main/README.md#screen-capture-mouse-events).

So concretely, my understanding of this is that this would be done as follows:

```
 let controller = new CaptureController();
 controller.oncapturedmousechange = ...
 let stream = await navigator.mediaDevices.getDisplayMedia({
   controller: controller,
   video: { advanced: [{cursor: "never"}] }
 });
 ...
```

Per the [Screen Capture spec](https://w3c.github.io/mediacapture-screen-share/#constrainable-properties) this does not affect what is presented to the user during permission request. However this would ask to [omit the cursor from the captured display surface[https://w3c.github.io/mediacapture-screen-share/#cursorcaptureconstraint].

So the TL;DR: I personally think we could
1. Explicitly mention that "cursor" constraint is used to control whether the cursor is captured in the use case description.
2. Have a small example (such as mine above if that's actually correct!).

**Comment by eladalon1983** [comment]
> video: { advanced: [{cursor: "never"}] }

I think `video: {cursor: "never"}`...?

**Comment by eladalon1983** [comment]
If you send a PR, I'll review it.
