### ISSUE TITLE
Add code examples

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#16]
The screen capture spec has an [basic example](https://w3c.github.io/mediacapture-screen-share/#example). I think we can similarly add a very basic one for this proposal (note that [video is actually true by default](https://w3c.github.io/mediacapture-screen-share/#dom-displaymediastreamoptions)):

```
  let controller = new CaptureController();
  controller.oncapturedmousechange = (event) => {
    console.log(`surfaceX=${event.surfaceX}, surfaceY=${event.surfaceY}`);
  }
  let mediaStream = await navigator.mediaDevices.getDisplayMedia({
    controller: controller
  });
  videoElement.srcObject = mediaStream;
```

Maybe we can also have some code examples to illustrate how `RTCDataChannel` can be used for peer-to-peer communication (#13) and how `cursor` constraint can be used to hide the mouse cursor for "efficiency enhancements during RTC" (#15).

Perhaps it should be in both the text of the spec and the explainer.

**Comment by eladalon1983** [comment]
Wrt an example - sure, please feel free to send a PR! (I'd remove the `videoElement` line.)

> Maybe we can also have some code examples to illustrate how RTCDataChannel can be used for peer-to-peer communication (https://github.com/screen-share/mouse-events/issues/13)

Maybe. I worry that it might be a bit too involved. Wdyt? How many lines would it be?

> and how cursor constraint can be used to hide the mouse cursor for "efficiency enhancements during RTC" (https://github.com/screen-share/mouse-events/issues/15).

AFAICT these aren't yet implemented, so adding that atm might be misleading to some.

> Perhaps it should be in both the text of the spec and the explainer.

That works for me.

**Comment by fred-wang** [comment]
I had opened one PR for that some days ago: https://github.com/screen-share/captured-mouse-events/pulls

**Comment by fred-wang** [comment]
Fixed by https://github.com/screen-share/captured-mouse-events/pull/18
