### ISSUE TITLE
Add Privacy/Security considerations sections

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#17]
This is mostly a reminder for the future when the spec is more advanced.

Currently we have this [in the spec](https://screen-share.github.io/mouse-events/#captured-mouse-change-event):

> But what if the application wishes to programmatically observe the location of the cursor? That can be done by scanning each frame and employing heuristics to detect the cursor. But that's neither simple, nor efficient, nor robust.

> CapturedMouseEvent exposes to an application the user's interaction with another application, or even with the operating system itself, calling for more scrutiny in which information may safely be exposed. At present, only information already available to the capturing application is exposed - the mouse coordinates.

The README also mentions potential problems for [future extensions](https://github.com/screen-share/mouse-events/tree/main#potential-discussed-but-not-currently-planned).

**Comment by eladalon1983** [comment]
> This is mostly a reminder for the future when the spec is more advanced.

How about we apply some label like `later-action-expected` and close the issue, so that the list of open issues will reflect what's actionable?

**Comment by fred-wang** [comment]
I think we can use labels to filter issues, but best practice is to keep issues open until they are resolved.

**Comment by eladalon1983** [comment]
> best practice is to keep issues open until they are resolved

What about issues that aren't issues **yet**? :-)

**Comment by fred-wang** [comment]
@eladalon1983 By not an issue yet, I assume you mean that there are no privacy/security thing to report with only mouse coordinates?

To clarify the rationale for this bug report, the W3C TAG review process involves answering to [Self-Review Questionnaire: Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/) and one of them is even [whether we have such Security/Privacy sections in the spec](https://www.w3.org/TR/security-privacy-questionnaire/#considerations).

I think putting this in two separate sections is also easier to read than the [3 different places I mentioned in the initial description](https://github.com/screen-share/captured-mouse-events/issues/17#issue-1771732661) or even conversations that happened in other venues.

We will have to answer these privacy/security questions at some point anyway before shipping the first implementation, so the earlier we document thing the better IMHO.

So the TL;DR is let's create these sections with at least "There are no known privacy/security impacts of the features in this specification." and elaborating a bit why before closing this issue. WDYT?

I can try a PR if you want.

**Comment by eladalon1983** [comment]
> So the TL;DR is let's create these sections with at least "There are no known privacy/security impacts of the features in this specification." and elaborating a bit why before closing this issue. WDYT?

That works for me - explicitly discussing the s&p considerations of the current spec and closing the issue, rather than leaving it open in anticipation of future changes.

> I can try a PR if you want.

That'd be great.

**Comment by fred-wang** [comment]
I think we can close this issue now that we have https://screen-share.github.io/captured-mouse-events/#privacy-and-security-considerations

Let's iterate later if necessary.
