### ISSUE TITLE
Add a w3c.json file

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#20]
Apparently this would be needed to get the WebIDL imported by external tools, see

https://github.com/w3c/browser-specs/pull/941#issuecomment-1536252404
https://github.com/w3c/browser-specs/issues/945

I checked https://w3c.github.io/w3c.json.html but I'm not sure what would be the proper `repo-type` value for an Unofficial Draft.

**Comment by eladalon1983** [comment]
@dontcallmedom, wdyt?

**Comment by dontcallmedom** [comment]
I'd suggest `cg-report`

**Comment by fred-wang** [comment]
@dontcallmedom Thanks!

@eladalon1983 Do you plan to do it or should I send a PR?

**Comment by eladalon1983** [comment]
Does the `w3c.json` file I've just added work?

**Comment by dontcallmedom** [comment]
LGTM

**Comment by fred-wang** [comment]
Thanks!

I guess we can close now.
