### ISSUE TITLE
Coordinate validation in CapturedMouseEvent's constructor

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#7]
The spec mentions that the only legal negative value for CapturedMouseEvent's surfaceX/surfaceY is -1.

What happens if someone manually creates a CapturedMouseEvent via CapturedMouseEventInit, with some negative values of surfaceX/surfaceY other than -1? Should this raise an error? Clamp values to -1?

Similarly what happens if someone specificies one of surfaceX/surfaceY being -1 and the other nonnegative? It seems it's a legal state per the spec, but without interpretation.

**Comment by eladalon1983** [comment]
> The spec mentions that the only legal value for CapturedMouseEvent's surfaceX/surfaceY is -1.

The spec says it's the only legal **negative** value. All positive values are legal. (You're most welcome to send a PR with a clarification.)

> What happens if someone manually creates a CapturedMouseEvent via CapturedMouseEventInit

That this is possible is a mistake. Would you send in a PR to fix this?

**Comment by fred-wang** [comment]
> The spec says it's the only legal negative value. All positive values are legal. (You're most welcome to send a PR with a clarification.)

Yes that's what I meant. Fixed in the description :-)

> That this is possible is a mistake. Would you send in a PR to fix this?

Sure, but I guess we need to agree on the way to fix that first...

To clarify what I meant, here is a similar testcase with MouseEvent:

```
  <!DOCTYPE html>
  <script>
    [
      new MouseEvent("dblclick", {screenX: -3, screenY: -1}),
      new MouseEvent("dblclick", {screenX: -1, screenY: 7}),
    ].forEach(e => {
      console.log(`screenX=${e.screenX}, screenY=${e.screenY}`);
    });
  </script>
```

the MouseEvents will be properly created with the specified parameters.

Now if we do the same for CapturedMouseEvent/surfaceX/surfaceY, the first constructor would receive the value -3 on one coordinate (which is invalid per the spec) while the former has a -1 on only one coordinate (to which the spec does not provide any interpretation).

I see two options: either treat all these cases as (-1, -1) or throw an exception.

**Comment by eladalon1983** [comment]
> I see two options: either treat all these cases as (-1, -1) or throw an exception.

There's also the option of preventing Web apps from instantiating `CapturedMouseEvent`. A precedent is [MediaStreamTrack](https://www.w3.org/TR/mediacapture-streams/#dom-mediastreamtrack). IIANM, simply removing the ctor from the IDL will achieve that. The benefit of this approach is that it minimizes spec and code. Wdyt?

**Comment by fred-wang** [comment]
I don't have strong opinion on this, but for the use cases mentioned in the spec a constructor is indeed unnecessary.

My guess would be that it's preferable to stay consistent with other Event interfaces, not to confuse web developers, and things like MouseEvent seem to provide a constructor. I see BeforeUnloadEvent does not have a constructor, but it also does not have actual attributes to set.

Another thing I can think of is how we are going to test the feature of this via WPT. It might be convenient to have a constructor to emulate a CapturedMouseEvent, directly in the wpt test or via the testdriver infrastructure (disclaimer: This is mostly speculation from my side at this stage).

I think the added spec/code/tests for the constructor would not be that big anyway...

**Comment by eladalon1983** [comment]
> My guess would be that it's preferable to stay consistent with other Event interfaces, not to confuse web developers

Adding a ctor would be easier than removing it later on, though.

> Another thing I can think of is how we are going to test the feature of this via WPT

It's possible to test the event's individual fields, rather than construct one and compare the events directly.

@beaufortfrancois, any thoughts? Any style guidelines you're aware of?

**Comment by eladalon1983** [comment]
Following our discussions elsewhere (e.g. [issue #8](https://github.com/screen-share/mouse-events/issues/8)), it seems like we will indeed be producing a ctor. In that case, I think the validation should reflect the following pseudocode:
```js
if (type != "capturedmousechange") {
  raise SomeException();
} else if ((surfaceX < 0 && surfaceX != -1) || (surfaceY < 0 && surfaceY != -1)) {
  raise SomeException();
} else if ((surfaceX == -1) != (surfaceY== -1)) {
  raise SomeException();
}
```
Wdyt, @fred-wang? (And assuming you're on board - would you send a PR?)

**Comment by fred-wang** [comment]
@eladalon1983 OK sounds good to me, I'll check in more details and work on PRs and the CL tomorrow. It seems `console.log(new MouseEvent("unknown_type"));` is a valid thing though. And for the others, I guess we want to throw  `RangeError` exceptions.

**Comment by eladalon1983** [comment]
> It seems `console.log(new MouseEvent("unknown_type"));` is a valid thing though.

Possibly the rationale is support for future extensions? Assuming other events behave similarly, I'm fine doing the same (i.e. not raising an exception).

> And for the others, I guess we want to throw `RangeError` exceptions.

Makes sense to me.

**Comment by fred-wang** [comment]
OK I tried something at https://chromium-review.googlesource.com/c/chromium/src/+/4517372

I guess the only diff is that ">= -1"  is equivalent to ">= 0 || == -1" for integers, I'm not distinguishing the different invalid cases.

Will try and send a PR later today.

**Comment by fred-wang** [comment]
> Will try and send a PR later today.

@eladalon1983 Done.

**Comment by fred-wang** [comment]
Fixed by https://github.com/screen-share/mouse-events/pull/11
