### ISSUE TITLE
DOMString type and Event options for CapturedMouseEvent's constructor

### ISSUE THREAD

**Issue by fred-wang** [screen-share/captured-mouse-events#8]
Current the IDL is as follows:

```
[Exposed=Window]
interface CapturedMouseEvent : Event {
  constructor(optional CapturedMouseEventInit eventInitDict = {});
  readonly attribute long surfaceX;
  readonly attribute long surfaceY;
};

dictionary CapturedMouseEventInit {
  long surfaceX = -1;
  long surfaceY = -1;
};
```

The constructor of Event is defined in https://dom.spec.whatwg.org/#interface-event and takes a DOMString `type` and optional EventInit. As I read the current spec, this would mean CapturedMouseEvent just passes an empty EventInit to Event while the type is undefined.

Comparing with `MouseEvent`, the IDL should rather make `CapturedMouseEventInit` derive from `EventInit` so that the parameters of Event are also accepted ; and accept an extra `type` parameter that is just passed to the constructor of Event.

One can argue whether we really need to have a `type` argument to CapturedMouseEvent's contructor (instead of a hardcoded value passed to Event's constructor). I guess that can be useful if we refine with more mouse types (e.g. click) in the future. I see BlobEvent's constructor does accept such a `type` argument even though internally it's always called `dataavailable`:

https://w3c.github.io/mediacapture-record/#blobevent
https://w3c.github.io/mediacapture-record/#event-summary

**Comment by fred-wang** [comment]
Oh, and I guess given https://screen-share.github.io/mouse-events/#dom-capturecontroller-oncapturedmousechange the idea would be to use `capturedmousechange` as a value for the `type` argument ?

**Comment by eladalon1983** [comment]
This all makes sense to me. Would you like to produce a PR?

**Comment by fred-wang** [comment]
@eladalon1983 Just sent a PR for this one too.

**Comment by fred-wang** [comment]
I believe this was fixed by the PR, so closing.
